openapi: 3.0.2
info:
  version: '1.1'
  title: SFG Beer Works Distributor API
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
  contact:
    name: John Thompson
    url: 'https://springframework.guru'
servers:
  - url: 'http://localhost:8080'
    description: Local Host
paths:
  /api/v1/order/status:
    post:
      description: Webhook post to reecive notifcations of order status changes.
      requestBody:
        description: Order Status Update
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  format: uuid
                orderStatus:
                  $ref: '#/components/schemas/OrderStatusUpdate'
      responses:
        '200':
          description: Okay
components:
  schemas:
    BaseItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        version:
          type: integer
        createdDate:
          type: string
          format: date-time
        lastModifiedDate:
          type: string
          format: date-time
    OrderStatusEnum:
      type: string
      enum:
        - NEW
        - READY
        - PICKED_UP
    OrderStatusUpdate:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        orderId:
          type: string
          format: uuid
        orderStatus:
          $ref: '#/components/schemas/OrderStatusEnum'
